# Starship prompt configuration

add_newline = false
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$dart\
$nodejs\
$java\
$kubernetes\
$aws\
$docker_context\
$character
"""
right_format = """$all"""
command_timeout = 1000

# Directory Configuration
[directory]
style = "blue"
truncation_length = 3
truncation_symbol = "…/"

# Character Configuration
[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

# Git Branch Configuration
[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bright-black"
symbol = " "


[git_status]
format = "[($conflicted$untracked$modified$staged$renamed$deleted)]($style) [$ahead_behind]($style) [$stashed]($style)"
style = "cyan"
conflicted = "⚠️"
untracked = "✚"
modified = "✎"
staged = "✓"
stashed = "≡"
# Git State Configuration
[git_state]
format = '([$state($progress_current/$progress_total)]($style)) '
style = "bright-black"

# Command Duration Configuration
[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 2_000 # Show if command took more than 2 seconds
show_milliseconds = true

# Python Configuration
[python]
format = "[🐍 $virtualenv]($style) "
style = "bright-black"

# AWS Configuration
[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = "bold blue"
symbol = " "

# Kubernetes Configuration
[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context(\($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

# Docker Context Configuration
[docker_context]
disabled = true

# Dart Configuration
[dart]
symbol = "  "
format = "[ $symbol]($style)"
style = "lavender"
# Node.js Configuration
[nodejs]
format = "[  ]($style) "
style = "green"

# Java Configuration
[java]
format = "[ ]($style) "
style = "red"

# Custom Color Palette (Catppuccin Mocha)
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

